apiVersion: v1
kind: Secret
metadata:
  name: contract-secret
  namespace: sharetrip
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:<password>@postgres:5432/sharetrip_contract?sslmode=disable"
