apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: sharetrip
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:<password>@postgres:5432/sharetrip?sslmode=disable"
