apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: sharetrip
data:
  HTTP_ADDR: ":8081"
  KAFKA_BROKERS: "kafka:9092"
  TRIP_EVENTS_TOPIC: "trip.events"
  KAFKA_GROUP_ID: "notification-service"
