services:
  postgres:
    image: postgres:16
    container_name: sharetrip-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sharetrip
    ports:
      - "6544:5432"
    volumes:
      - sharetrip_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sharetrip"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.19.1
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: postgres:5432/sharetrip?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: password
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  loki:
    image: grafana/loki:3.7.0
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ../loki/config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../grafana/dashboards:/etc/grafana/dashboards:ro
    depends_on:
      - loki
      - prometheus

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: run /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ../alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ../logs:/var/log/myapp:ro
    depends_on:
      - loki

volumes:
  sharetrip_pgdata:
  loki_data:
  grafana_data:
  prometheus_data:
