// Code generated by MockGen. DO NOT EDIT.
// Source: contract_checker.go
//
// Generated by this command:
//
//	mockgen -source=contract_checker.go -destination=mocks/contract_checker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	service "job4j.ru/share-trip/internal/service"
)

// MockContractChecker is a mock of ContractChecker interface.
type MockContractChecker struct {
	ctrl     *gomock.Controller
	recorder *MockContractCheckerMockRecorder
	isgomock struct{}
}

// MockContractCheckerMockRecorder is the mock recorder for MockContractChecker.
type MockContractCheckerMockRecorder struct {
	mock *MockContractChecker
}

// NewMockContractChecker creates a new mock instance.
func NewMockContractChecker(ctrl *gomock.Controller) *MockContractChecker {
	mock := &MockContractChecker{ctrl: ctrl}
	mock.recorder = &MockContractCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractChecker) EXPECT() *MockContractCheckerMockRecorder {
	return m.recorder
}

// CheckService mocks base method.
func (m *MockContractChecker) CheckService(ctx context.Context, companyID, serviceCode string) (service.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckService", ctx, companyID, serviceCode)
	ret0, _ := ret[0].(service.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckService indicates an expected call of CheckService.
func (mr *MockContractCheckerMockRecorder) CheckService(ctx, companyID, serviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckService", reflect.TypeOf((*MockContractChecker)(nil).CheckService), ctx, companyID, serviceCode)
}
